version: '3.7'

# after first initial build some django doesnt work
# you need to stop containers and run again , so django will work then
services:

  web:

    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    #command: gunicorn crud_project.wsgi -b 0.0.0.0:8000

    environment:
      - ENVIRONMENT=development
      # double dollar sign is used here to escape error
      - SECRET_KEY=8xfjiv8fcla7_((4xiyhuuboes8875-mi3v(np+++g73x9m$$66
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DEBUG=1
      - REDIS_URL=redis://moreblog-redis:6379/0

    # A new folder ./code/ will be created in the root dir of
    # container and
    # All code changed in directory /code/ inside container
    # will be sync with out host folder . (local) where this file sits
    # and vice versa
    volumes:

      - .:/code

    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11

    # this means new volume (books_)?????????postgres_data will be created
    # in our host /var/lib/docker/volumes
    # and this folder/volume will be populated with data from
    # container's folder /var/lib/postgresql/data/
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    # this database service will start after red service is running
    depends_on:
      - red


  # this will start a service red from image specified.
  red:
    container_name: moreblog-redis
    image: redis:5.0.3-alpine


volumes:

  postgres_data: